CREATE TABLE RECIPE(
  ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  NUMBER_OF_SERVINGS INTEGER NOT NULL,
  INGREDIENTS VARCHAR(100),
  INSTRUCTIONS VARCHAR(100),
  IS_VEG BOOLEAN,
  UNIQUE(NAME));